// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod asterai {
    pub mod host {
        #[allow(dead_code, clippy::all)]
        pub mod api {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct RuntimeInfo {
                pub version: _rt::String,
            }
            impl ::core::fmt::Debug for RuntimeInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("RuntimeInfo")
                        .field("version", &self.version)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ParamInfo {
                pub name: _rt::String,
                pub type_name: _rt::String,
                pub type_schema: _rt::String,
            }
            impl ::core::fmt::Debug for ParamInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ParamInfo")
                        .field("name", &self.name)
                        .field("type-name", &self.type_name)
                        .field("type-schema", &self.type_schema)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct TypeInfo {
                pub type_name: _rt::String,
                pub type_schema: _rt::String,
            }
            impl ::core::fmt::Debug for TypeInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("TypeInfo")
                        .field("type-name", &self.type_name)
                        .field("type-schema", &self.type_schema)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct FunctionInfo {
                pub name: _rt::String,
                pub interface_name: Option<_rt::String>,
                pub description: Option<_rt::String>,
                pub inputs: _rt::Vec<ParamInfo>,
                pub output: Option<TypeInfo>,
            }
            impl ::core::fmt::Debug for FunctionInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("FunctionInfo")
                        .field("name", &self.name)
                        .field("interface-name", &self.interface_name)
                        .field("description", &self.description)
                        .field("inputs", &self.inputs)
                        .field("output", &self.output)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ComponentInfo {
                pub name: _rt::String,
                pub version: _rt::String,
                pub interfaces: _rt::Vec<_rt::String>,
                pub description: Option<_rt::String>,
                pub functions: _rt::Vec<FunctionInfo>,
            }
            impl ::core::fmt::Debug for ComponentInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ComponentInfo")
                        .field("name", &self.name)
                        .field("version", &self.version)
                        .field("interfaces", &self.interfaces)
                        .field("description", &self.description)
                        .field("functions", &self.functions)
                        .finish()
                }
            }
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallErrorKind {
                ComponentNotFound,
                FunctionNotFound,
                InvalidArgs,
                InvocationFailed,
                SerializationFailed,
            }
            impl ::core::fmt::Debug for CallErrorKind {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    match self {
                        CallErrorKind::ComponentNotFound => {
                            f.debug_tuple("CallErrorKind::ComponentNotFound").finish()
                        }
                        CallErrorKind::FunctionNotFound => {
                            f.debug_tuple("CallErrorKind::FunctionNotFound").finish()
                        }
                        CallErrorKind::InvalidArgs => {
                            f.debug_tuple("CallErrorKind::InvalidArgs").finish()
                        }
                        CallErrorKind::InvocationFailed => {
                            f.debug_tuple("CallErrorKind::InvocationFailed").finish()
                        }
                        CallErrorKind::SerializationFailed => {
                            f.debug_tuple("CallErrorKind::SerializationFailed").finish()
                        }
                    }
                }
            }
            impl CallErrorKind {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallErrorKind {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }
                    match val {
                        0 => CallErrorKind::ComponentNotFound,
                        1 => CallErrorKind::FunctionNotFound,
                        2 => CallErrorKind::InvalidArgs,
                        3 => CallErrorKind::InvocationFailed,
                        4 => CallErrorKind::SerializationFailed,
                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }
            #[derive(Clone)]
            pub struct CallError {
                pub kind: CallErrorKind,
                pub message: _rt::String,
            }
            impl ::core::fmt::Debug for CallError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("CallError")
                        .field("kind", &self.kind)
                        .field("message", &self.message)
                        .finish()
                }
            }
            impl ::core::fmt::Display for CallError {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl std::error::Error for CallError {}
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_runtime_info() -> RuntimeInfo {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "get-runtime-info"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let len3 = l2;
                    let bytes3 = _rt::Vec::from_raw_parts(l1.cast(), len3, len3);
                    RuntimeInfo {
                        version: _rt::string_lift(bytes3),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_components() -> _rt::Vec<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "list-components"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let base52 = l1;
                    let len52 = l2;
                    let mut result52 = _rt::Vec::with_capacity(len52);
                    for i in 0..len52 {
                        let base = base52.add(i * 44);
                        let e52 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base.add(4).cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base.add(8).cast::<*mut u8>();
                            let l7 = *base.add(12).cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = *base.add(16).cast::<*mut u8>();
                            let l10 = *base.add(20).cast::<usize>();
                            let base14 = l9;
                            let len14 = l10;
                            let mut result14 = _rt::Vec::with_capacity(len14);
                            for i in 0..len14 {
                                let base = base14.add(i * 8);
                                let e14 = {
                                    let l11 = *base.add(0).cast::<*mut u8>();
                                    let l12 = *base.add(4).cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                result14.push(e14);
                            }
                            _rt::cabi_dealloc(base14, len14 * 8, 4);
                            let l15 = i32::from(*base.add(24).cast::<u8>());
                            let l19 = *base.add(36).cast::<*mut u8>();
                            let l20 = *base.add(40).cast::<usize>();
                            let base51 = l19;
                            let len51 = l20;
                            let mut result51 = _rt::Vec::with_capacity(len51);
                            for i in 0..len51 {
                                let base = base51.add(i * 60);
                                let e51 = {
                                    let l21 = *base.add(0).cast::<*mut u8>();
                                    let l22 = *base.add(4).cast::<usize>();
                                    let len23 = l22;
                                    let bytes23 = _rt::Vec::from_raw_parts(
                                        l21.cast(),
                                        len23,
                                        len23,
                                    );
                                    let l24 = i32::from(*base.add(8).cast::<u8>());
                                    let l28 = i32::from(*base.add(20).cast::<u8>());
                                    let l32 = *base.add(32).cast::<*mut u8>();
                                    let l33 = *base.add(36).cast::<usize>();
                                    let base43 = l32;
                                    let len43 = l33;
                                    let mut result43 = _rt::Vec::with_capacity(len43);
                                    for i in 0..len43 {
                                        let base = base43.add(i * 24);
                                        let e43 = {
                                            let l34 = *base.add(0).cast::<*mut u8>();
                                            let l35 = *base.add(4).cast::<usize>();
                                            let len36 = l35;
                                            let bytes36 = _rt::Vec::from_raw_parts(
                                                l34.cast(),
                                                len36,
                                                len36,
                                            );
                                            let l37 = *base.add(8).cast::<*mut u8>();
                                            let l38 = *base.add(12).cast::<usize>();
                                            let len39 = l38;
                                            let bytes39 = _rt::Vec::from_raw_parts(
                                                l37.cast(),
                                                len39,
                                                len39,
                                            );
                                            let l40 = *base.add(16).cast::<*mut u8>();
                                            let l41 = *base.add(20).cast::<usize>();
                                            let len42 = l41;
                                            let bytes42 = _rt::Vec::from_raw_parts(
                                                l40.cast(),
                                                len42,
                                                len42,
                                            );
                                            ParamInfo {
                                                name: _rt::string_lift(bytes36),
                                                type_name: _rt::string_lift(bytes39),
                                                type_schema: _rt::string_lift(bytes42),
                                            }
                                        };
                                        result43.push(e43);
                                    }
                                    _rt::cabi_dealloc(base43, len43 * 24, 4);
                                    let l44 = i32::from(*base.add(40).cast::<u8>());
                                    FunctionInfo {
                                        name: _rt::string_lift(bytes23),
                                        interface_name: match l24 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l25 = *base.add(12).cast::<*mut u8>();
                                                    let l26 = *base.add(16).cast::<usize>();
                                                    let len27 = l26;
                                                    let bytes27 = _rt::Vec::from_raw_parts(
                                                        l25.cast(),
                                                        len27,
                                                        len27,
                                                    );
                                                    _rt::string_lift(bytes27)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        description: match l28 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l29 = *base.add(24).cast::<*mut u8>();
                                                    let l30 = *base.add(28).cast::<usize>();
                                                    let len31 = l30;
                                                    let bytes31 = _rt::Vec::from_raw_parts(
                                                        l29.cast(),
                                                        len31,
                                                        len31,
                                                    );
                                                    _rt::string_lift(bytes31)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        inputs: result43,
                                        output: match l44 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l45 = *base.add(44).cast::<*mut u8>();
                                                    let l46 = *base.add(48).cast::<usize>();
                                                    let len47 = l46;
                                                    let bytes47 = _rt::Vec::from_raw_parts(
                                                        l45.cast(),
                                                        len47,
                                                        len47,
                                                    );
                                                    let l48 = *base.add(52).cast::<*mut u8>();
                                                    let l49 = *base.add(56).cast::<usize>();
                                                    let len50 = l49;
                                                    let bytes50 = _rt::Vec::from_raw_parts(
                                                        l48.cast(),
                                                        len50,
                                                        len50,
                                                    );
                                                    TypeInfo {
                                                        type_name: _rt::string_lift(bytes47),
                                                        type_schema: _rt::string_lift(bytes50),
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                result51.push(e51);
                            }
                            _rt::cabi_dealloc(base51, len51 * 60, 4);
                            ComponentInfo {
                                name: _rt::string_lift(bytes5),
                                version: _rt::string_lift(bytes8),
                                interfaces: result14,
                                description: match l15 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l16 = *base.add(28).cast::<*mut u8>();
                                            let l17 = *base.add(32).cast::<usize>();
                                            let len18 = l17;
                                            let bytes18 = _rt::Vec::from_raw_parts(
                                                l16.cast(),
                                                len18,
                                                len18,
                                            );
                                            _rt::string_lift(bytes18)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                functions: result51,
                            }
                        };
                        result52.push(e52);
                    }
                    _rt::cabi_dealloc(base52, len52 * 44, 4);
                    result52
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn list_other_components() -> _rt::Vec<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 8]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
                    let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "list-other-components"]
                        fn wit_import(_: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0);
                    let l1 = *ptr0.add(0).cast::<*mut u8>();
                    let l2 = *ptr0.add(4).cast::<usize>();
                    let base52 = l1;
                    let len52 = l2;
                    let mut result52 = _rt::Vec::with_capacity(len52);
                    for i in 0..len52 {
                        let base = base52.add(i * 44);
                        let e52 = {
                            let l3 = *base.add(0).cast::<*mut u8>();
                            let l4 = *base.add(4).cast::<usize>();
                            let len5 = l4;
                            let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);
                            let l6 = *base.add(8).cast::<*mut u8>();
                            let l7 = *base.add(12).cast::<usize>();
                            let len8 = l7;
                            let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);
                            let l9 = *base.add(16).cast::<*mut u8>();
                            let l10 = *base.add(20).cast::<usize>();
                            let base14 = l9;
                            let len14 = l10;
                            let mut result14 = _rt::Vec::with_capacity(len14);
                            for i in 0..len14 {
                                let base = base14.add(i * 8);
                                let e14 = {
                                    let l11 = *base.add(0).cast::<*mut u8>();
                                    let l12 = *base.add(4).cast::<usize>();
                                    let len13 = l12;
                                    let bytes13 = _rt::Vec::from_raw_parts(
                                        l11.cast(),
                                        len13,
                                        len13,
                                    );
                                    _rt::string_lift(bytes13)
                                };
                                result14.push(e14);
                            }
                            _rt::cabi_dealloc(base14, len14 * 8, 4);
                            let l15 = i32::from(*base.add(24).cast::<u8>());
                            let l19 = *base.add(36).cast::<*mut u8>();
                            let l20 = *base.add(40).cast::<usize>();
                            let base51 = l19;
                            let len51 = l20;
                            let mut result51 = _rt::Vec::with_capacity(len51);
                            for i in 0..len51 {
                                let base = base51.add(i * 60);
                                let e51 = {
                                    let l21 = *base.add(0).cast::<*mut u8>();
                                    let l22 = *base.add(4).cast::<usize>();
                                    let len23 = l22;
                                    let bytes23 = _rt::Vec::from_raw_parts(
                                        l21.cast(),
                                        len23,
                                        len23,
                                    );
                                    let l24 = i32::from(*base.add(8).cast::<u8>());
                                    let l28 = i32::from(*base.add(20).cast::<u8>());
                                    let l32 = *base.add(32).cast::<*mut u8>();
                                    let l33 = *base.add(36).cast::<usize>();
                                    let base43 = l32;
                                    let len43 = l33;
                                    let mut result43 = _rt::Vec::with_capacity(len43);
                                    for i in 0..len43 {
                                        let base = base43.add(i * 24);
                                        let e43 = {
                                            let l34 = *base.add(0).cast::<*mut u8>();
                                            let l35 = *base.add(4).cast::<usize>();
                                            let len36 = l35;
                                            let bytes36 = _rt::Vec::from_raw_parts(
                                                l34.cast(),
                                                len36,
                                                len36,
                                            );
                                            let l37 = *base.add(8).cast::<*mut u8>();
                                            let l38 = *base.add(12).cast::<usize>();
                                            let len39 = l38;
                                            let bytes39 = _rt::Vec::from_raw_parts(
                                                l37.cast(),
                                                len39,
                                                len39,
                                            );
                                            let l40 = *base.add(16).cast::<*mut u8>();
                                            let l41 = *base.add(20).cast::<usize>();
                                            let len42 = l41;
                                            let bytes42 = _rt::Vec::from_raw_parts(
                                                l40.cast(),
                                                len42,
                                                len42,
                                            );
                                            ParamInfo {
                                                name: _rt::string_lift(bytes36),
                                                type_name: _rt::string_lift(bytes39),
                                                type_schema: _rt::string_lift(bytes42),
                                            }
                                        };
                                        result43.push(e43);
                                    }
                                    _rt::cabi_dealloc(base43, len43 * 24, 4);
                                    let l44 = i32::from(*base.add(40).cast::<u8>());
                                    FunctionInfo {
                                        name: _rt::string_lift(bytes23),
                                        interface_name: match l24 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l25 = *base.add(12).cast::<*mut u8>();
                                                    let l26 = *base.add(16).cast::<usize>();
                                                    let len27 = l26;
                                                    let bytes27 = _rt::Vec::from_raw_parts(
                                                        l25.cast(),
                                                        len27,
                                                        len27,
                                                    );
                                                    _rt::string_lift(bytes27)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        description: match l28 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l29 = *base.add(24).cast::<*mut u8>();
                                                    let l30 = *base.add(28).cast::<usize>();
                                                    let len31 = l30;
                                                    let bytes31 = _rt::Vec::from_raw_parts(
                                                        l29.cast(),
                                                        len31,
                                                        len31,
                                                    );
                                                    _rt::string_lift(bytes31)
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                        inputs: result43,
                                        output: match l44 {
                                            0 => None,
                                            1 => {
                                                let e = {
                                                    let l45 = *base.add(44).cast::<*mut u8>();
                                                    let l46 = *base.add(48).cast::<usize>();
                                                    let len47 = l46;
                                                    let bytes47 = _rt::Vec::from_raw_parts(
                                                        l45.cast(),
                                                        len47,
                                                        len47,
                                                    );
                                                    let l48 = *base.add(52).cast::<*mut u8>();
                                                    let l49 = *base.add(56).cast::<usize>();
                                                    let len50 = l49;
                                                    let bytes50 = _rt::Vec::from_raw_parts(
                                                        l48.cast(),
                                                        len50,
                                                        len50,
                                                    );
                                                    TypeInfo {
                                                        type_name: _rt::string_lift(bytes47),
                                                        type_schema: _rt::string_lift(bytes50),
                                                    }
                                                };
                                                Some(e)
                                            }
                                            _ => _rt::invalid_enum_discriminant(),
                                        },
                                    }
                                };
                                result51.push(e51);
                            }
                            _rt::cabi_dealloc(base51, len51 * 60, 4);
                            ComponentInfo {
                                name: _rt::string_lift(bytes5),
                                version: _rt::string_lift(bytes8),
                                interfaces: result14,
                                description: match l15 {
                                    0 => None,
                                    1 => {
                                        let e = {
                                            let l16 = *base.add(28).cast::<*mut u8>();
                                            let l17 = *base.add(32).cast::<usize>();
                                            let len18 = l17;
                                            let bytes18 = _rt::Vec::from_raw_parts(
                                                l16.cast(),
                                                len18,
                                                len18,
                                            );
                                            _rt::string_lift(bytes18)
                                        };
                                        Some(e)
                                    }
                                    _ => _rt::invalid_enum_discriminant(),
                                },
                                functions: result51,
                            }
                        };
                        result52.push(e52);
                    }
                    _rt::cabi_dealloc(base52, len52 * 44, 4);
                    result52
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn get_component(name: &str) -> Option<ComponentInfo> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 48]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 48]);
                    let vec0 = name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "get-component"]
                        fn wit_import(_: *mut u8, _: usize, _: *mut u8);
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8, _: usize, _: *mut u8) {
                        unreachable!()
                    }
                    wit_import(ptr0.cast_mut(), len0, ptr1);
                    let l2 = i32::from(*ptr1.add(0).cast::<u8>());
                    match l2 {
                        0 => None,
                        1 => {
                            let e = {
                                let l3 = *ptr1.add(4).cast::<*mut u8>();
                                let l4 = *ptr1.add(8).cast::<usize>();
                                let len5 = l4;
                                let bytes5 = _rt::Vec::from_raw_parts(
                                    l3.cast(),
                                    len5,
                                    len5,
                                );
                                let l6 = *ptr1.add(12).cast::<*mut u8>();
                                let l7 = *ptr1.add(16).cast::<usize>();
                                let len8 = l7;
                                let bytes8 = _rt::Vec::from_raw_parts(
                                    l6.cast(),
                                    len8,
                                    len8,
                                );
                                let l9 = *ptr1.add(20).cast::<*mut u8>();
                                let l10 = *ptr1.add(24).cast::<usize>();
                                let base14 = l9;
                                let len14 = l10;
                                let mut result14 = _rt::Vec::with_capacity(len14);
                                for i in 0..len14 {
                                    let base = base14.add(i * 8);
                                    let e14 = {
                                        let l11 = *base.add(0).cast::<*mut u8>();
                                        let l12 = *base.add(4).cast::<usize>();
                                        let len13 = l12;
                                        let bytes13 = _rt::Vec::from_raw_parts(
                                            l11.cast(),
                                            len13,
                                            len13,
                                        );
                                        _rt::string_lift(bytes13)
                                    };
                                    result14.push(e14);
                                }
                                _rt::cabi_dealloc(base14, len14 * 8, 4);
                                let l15 = i32::from(*ptr1.add(28).cast::<u8>());
                                let l19 = *ptr1.add(40).cast::<*mut u8>();
                                let l20 = *ptr1.add(44).cast::<usize>();
                                let base51 = l19;
                                let len51 = l20;
                                let mut result51 = _rt::Vec::with_capacity(len51);
                                for i in 0..len51 {
                                    let base = base51.add(i * 60);
                                    let e51 = {
                                        let l21 = *base.add(0).cast::<*mut u8>();
                                        let l22 = *base.add(4).cast::<usize>();
                                        let len23 = l22;
                                        let bytes23 = _rt::Vec::from_raw_parts(
                                            l21.cast(),
                                            len23,
                                            len23,
                                        );
                                        let l24 = i32::from(*base.add(8).cast::<u8>());
                                        let l28 = i32::from(*base.add(20).cast::<u8>());
                                        let l32 = *base.add(32).cast::<*mut u8>();
                                        let l33 = *base.add(36).cast::<usize>();
                                        let base43 = l32;
                                        let len43 = l33;
                                        let mut result43 = _rt::Vec::with_capacity(len43);
                                        for i in 0..len43 {
                                            let base = base43.add(i * 24);
                                            let e43 = {
                                                let l34 = *base.add(0).cast::<*mut u8>();
                                                let l35 = *base.add(4).cast::<usize>();
                                                let len36 = l35;
                                                let bytes36 = _rt::Vec::from_raw_parts(
                                                    l34.cast(),
                                                    len36,
                                                    len36,
                                                );
                                                let l37 = *base.add(8).cast::<*mut u8>();
                                                let l38 = *base.add(12).cast::<usize>();
                                                let len39 = l38;
                                                let bytes39 = _rt::Vec::from_raw_parts(
                                                    l37.cast(),
                                                    len39,
                                                    len39,
                                                );
                                                let l40 = *base.add(16).cast::<*mut u8>();
                                                let l41 = *base.add(20).cast::<usize>();
                                                let len42 = l41;
                                                let bytes42 = _rt::Vec::from_raw_parts(
                                                    l40.cast(),
                                                    len42,
                                                    len42,
                                                );
                                                ParamInfo {
                                                    name: _rt::string_lift(bytes36),
                                                    type_name: _rt::string_lift(bytes39),
                                                    type_schema: _rt::string_lift(bytes42),
                                                }
                                            };
                                            result43.push(e43);
                                        }
                                        _rt::cabi_dealloc(base43, len43 * 24, 4);
                                        let l44 = i32::from(*base.add(40).cast::<u8>());
                                        FunctionInfo {
                                            name: _rt::string_lift(bytes23),
                                            interface_name: match l24 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l25 = *base.add(12).cast::<*mut u8>();
                                                        let l26 = *base.add(16).cast::<usize>();
                                                        let len27 = l26;
                                                        let bytes27 = _rt::Vec::from_raw_parts(
                                                            l25.cast(),
                                                            len27,
                                                            len27,
                                                        );
                                                        _rt::string_lift(bytes27)
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                            description: match l28 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l29 = *base.add(24).cast::<*mut u8>();
                                                        let l30 = *base.add(28).cast::<usize>();
                                                        let len31 = l30;
                                                        let bytes31 = _rt::Vec::from_raw_parts(
                                                            l29.cast(),
                                                            len31,
                                                            len31,
                                                        );
                                                        _rt::string_lift(bytes31)
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                            inputs: result43,
                                            output: match l44 {
                                                0 => None,
                                                1 => {
                                                    let e = {
                                                        let l45 = *base.add(44).cast::<*mut u8>();
                                                        let l46 = *base.add(48).cast::<usize>();
                                                        let len47 = l46;
                                                        let bytes47 = _rt::Vec::from_raw_parts(
                                                            l45.cast(),
                                                            len47,
                                                            len47,
                                                        );
                                                        let l48 = *base.add(52).cast::<*mut u8>();
                                                        let l49 = *base.add(56).cast::<usize>();
                                                        let len50 = l49;
                                                        let bytes50 = _rt::Vec::from_raw_parts(
                                                            l48.cast(),
                                                            len50,
                                                            len50,
                                                        );
                                                        TypeInfo {
                                                            type_name: _rt::string_lift(bytes47),
                                                            type_schema: _rt::string_lift(bytes50),
                                                        }
                                                    };
                                                    Some(e)
                                                }
                                                _ => _rt::invalid_enum_discriminant(),
                                            },
                                        }
                                    };
                                    result51.push(e51);
                                }
                                _rt::cabi_dealloc(base51, len51 * 60, 4);
                                ComponentInfo {
                                    name: _rt::string_lift(bytes5),
                                    version: _rt::string_lift(bytes8),
                                    interfaces: result14,
                                    description: match l15 {
                                        0 => None,
                                        1 => {
                                            let e = {
                                                let l16 = *ptr1.add(32).cast::<*mut u8>();
                                                let l17 = *ptr1.add(36).cast::<usize>();
                                                let len18 = l17;
                                                let bytes18 = _rt::Vec::from_raw_parts(
                                                    l16.cast(),
                                                    len18,
                                                    len18,
                                                );
                                                _rt::string_lift(bytes18)
                                            };
                                            Some(e)
                                        }
                                        _ => _rt::invalid_enum_discriminant(),
                                    },
                                    functions: result51,
                                }
                            };
                            Some(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn component_implements(
                component_name: &str,
                interface_name: &str,
            ) -> bool {
                unsafe {
                    let vec0 = component_name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = interface_name;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "component-implements"]
                        fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32;
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(_: *mut u8, _: usize, _: *mut u8, _: usize) -> i32 {
                        unreachable!()
                    }
                    let ret = wit_import(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1);
                    _rt::bool_lift(ret as u8)
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            pub fn call_component_function(
                component_name: &str,
                function_name: &str,
                args_json: &str,
            ) -> Result<_rt::String, CallError> {
                unsafe {
                    #[repr(align(4))]
                    struct RetArea([::core::mem::MaybeUninit<u8>; 16]);
                    let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
                    let vec0 = component_name;
                    let ptr0 = vec0.as_ptr().cast::<u8>();
                    let len0 = vec0.len();
                    let vec1 = function_name;
                    let ptr1 = vec1.as_ptr().cast::<u8>();
                    let len1 = vec1.len();
                    let vec2 = args_json;
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
                    #[cfg(target_arch = "wasm32")]
                    #[link(wasm_import_module = "asterai:host/api@1.0.0")]
                    extern "C" {
                        #[link_name = "call-component-function"]
                        fn wit_import(
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                            _: usize,
                            _: *mut u8,
                        );
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    fn wit_import(
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                        _: usize,
                        _: *mut u8,
                    ) {
                        unreachable!()
                    }
                    wit_import(
                        ptr0.cast_mut(),
                        len0,
                        ptr1.cast_mut(),
                        len1,
                        ptr2.cast_mut(),
                        len2,
                        ptr3,
                    );
                    let l4 = i32::from(*ptr3.add(0).cast::<u8>());
                    match l4 {
                        0 => {
                            let e = {
                                let l5 = *ptr3.add(4).cast::<*mut u8>();
                                let l6 = *ptr3.add(8).cast::<usize>();
                                let len7 = l6;
                                let bytes7 = _rt::Vec::from_raw_parts(
                                    l5.cast(),
                                    len7,
                                    len7,
                                );
                                _rt::string_lift(bytes7)
                            };
                            Ok(e)
                        }
                        1 => {
                            let e = {
                                let l8 = i32::from(*ptr3.add(4).cast::<u8>());
                                let l9 = *ptr3.add(8).cast::<*mut u8>();
                                let l10 = *ptr3.add(12).cast::<usize>();
                                let len11 = l10;
                                let bytes11 = _rt::Vec::from_raw_parts(
                                    l9.cast(),
                                    len11,
                                    len11,
                                );
                                CallError {
                                    kind: CallErrorKind::_lift(l8 as u8),
                                    message: _rt::string_lift(bytes11),
                                }
                            };
                            Err(e)
                        }
                        _ => _rt::invalid_enum_discriminant(),
                    }
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod asterbot {
    pub mod types {
        #[allow(dead_code, clippy::all)]
        pub mod types {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            use super::super::super::_rt;
            #[derive(Clone)]
            pub struct ToolParam {
                pub name: _rt::String,
                pub type_name: _rt::String,
            }
            impl ::core::fmt::Debug for ToolParam {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ToolParam")
                        .field("name", &self.name)
                        .field("type-name", &self.type_name)
                        .finish()
                }
            }
            #[derive(Clone)]
            pub struct ToolInfo {
                pub component_name: _rt::String,
                pub function_name: _rt::String,
                pub description: _rt::String,
                pub params: _rt::Vec<ToolParam>,
                pub return_type: _rt::String,
            }
            impl ::core::fmt::Debug for ToolInfo {
                fn fmt(
                    &self,
                    f: &mut ::core::fmt::Formatter<'_>,
                ) -> ::core::fmt::Result {
                    f.debug_struct("ToolInfo")
                        .field("component-name", &self.component_name)
                        .field("function-name", &self.function_name)
                        .field("description", &self.description)
                        .field("params", &self.params)
                        .field("return-type", &self.return_type)
                        .finish()
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod asterbot {
        pub mod types {
            #[allow(dead_code, clippy::all)]
            pub mod toolkit {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                pub type ToolInfo = super::super::super::super::asterbot::types::types::ToolInfo;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_list_tools_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::list_tools();
                    let ptr1 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
                    let vec11 = result0;
                    let len11 = vec11.len();
                    let layout11 = _rt::alloc::Layout::from_size_align_unchecked(
                        vec11.len() * 40,
                        4,
                    );
                    let result11 = if layout11.size() != 0 {
                        let ptr = _rt::alloc::alloc(layout11).cast::<u8>();
                        if ptr.is_null() {
                            _rt::alloc::handle_alloc_error(layout11);
                        }
                        ptr
                    } else {
                        ::core::ptr::null_mut()
                    };
                    for (i, e) in vec11.into_iter().enumerate() {
                        let base = result11.add(i * 40);
                        {
                            let super::super::super::super::asterbot::types::types::ToolInfo {
                                component_name: component_name2,
                                function_name: function_name2,
                                description: description2,
                                params: params2,
                                return_type: return_type2,
                            } = e;
                            let vec3 = (component_name2.into_bytes()).into_boxed_slice();
                            let ptr3 = vec3.as_ptr().cast::<u8>();
                            let len3 = vec3.len();
                            ::core::mem::forget(vec3);
                            *base.add(4).cast::<usize>() = len3;
                            *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                            let vec4 = (function_name2.into_bytes()).into_boxed_slice();
                            let ptr4 = vec4.as_ptr().cast::<u8>();
                            let len4 = vec4.len();
                            ::core::mem::forget(vec4);
                            *base.add(12).cast::<usize>() = len4;
                            *base.add(8).cast::<*mut u8>() = ptr4.cast_mut();
                            let vec5 = (description2.into_bytes()).into_boxed_slice();
                            let ptr5 = vec5.as_ptr().cast::<u8>();
                            let len5 = vec5.len();
                            ::core::mem::forget(vec5);
                            *base.add(20).cast::<usize>() = len5;
                            *base.add(16).cast::<*mut u8>() = ptr5.cast_mut();
                            let vec9 = params2;
                            let len9 = vec9.len();
                            let layout9 = _rt::alloc::Layout::from_size_align_unchecked(
                                vec9.len() * 16,
                                4,
                            );
                            let result9 = if layout9.size() != 0 {
                                let ptr = _rt::alloc::alloc(layout9).cast::<u8>();
                                if ptr.is_null() {
                                    _rt::alloc::handle_alloc_error(layout9);
                                }
                                ptr
                            } else {
                                ::core::ptr::null_mut()
                            };
                            for (i, e) in vec9.into_iter().enumerate() {
                                let base = result9.add(i * 16);
                                {
                                    let super::super::super::super::asterbot::types::types::ToolParam {
                                        name: name6,
                                        type_name: type_name6,
                                    } = e;
                                    let vec7 = (name6.into_bytes()).into_boxed_slice();
                                    let ptr7 = vec7.as_ptr().cast::<u8>();
                                    let len7 = vec7.len();
                                    ::core::mem::forget(vec7);
                                    *base.add(4).cast::<usize>() = len7;
                                    *base.add(0).cast::<*mut u8>() = ptr7.cast_mut();
                                    let vec8 = (type_name6.into_bytes()).into_boxed_slice();
                                    let ptr8 = vec8.as_ptr().cast::<u8>();
                                    let len8 = vec8.len();
                                    ::core::mem::forget(vec8);
                                    *base.add(12).cast::<usize>() = len8;
                                    *base.add(8).cast::<*mut u8>() = ptr8.cast_mut();
                                }
                            }
                            *base.add(28).cast::<usize>() = len9;
                            *base.add(24).cast::<*mut u8>() = result9;
                            let vec10 = (return_type2.into_bytes()).into_boxed_slice();
                            let ptr10 = vec10.as_ptr().cast::<u8>();
                            let len10 = vec10.len();
                            ::core::mem::forget(vec10);
                            *base.add(36).cast::<usize>() = len10;
                            *base.add(32).cast::<*mut u8>() = ptr10.cast_mut();
                        }
                    }
                    *ptr1.add(4).cast::<usize>() = len11;
                    *ptr1.add(0).cast::<*mut u8>() = result11;
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_list_tools<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0.add(4).cast::<usize>();
                    let base17 = l0;
                    let len17 = l1;
                    for i in 0..len17 {
                        let base = base17.add(i * 40);
                        {
                            let l2 = *base.add(0).cast::<*mut u8>();
                            let l3 = *base.add(4).cast::<usize>();
                            _rt::cabi_dealloc(l2, l3, 1);
                            let l4 = *base.add(8).cast::<*mut u8>();
                            let l5 = *base.add(12).cast::<usize>();
                            _rt::cabi_dealloc(l4, l5, 1);
                            let l6 = *base.add(16).cast::<*mut u8>();
                            let l7 = *base.add(20).cast::<usize>();
                            _rt::cabi_dealloc(l6, l7, 1);
                            let l8 = *base.add(24).cast::<*mut u8>();
                            let l9 = *base.add(28).cast::<usize>();
                            let base14 = l8;
                            let len14 = l9;
                            for i in 0..len14 {
                                let base = base14.add(i * 16);
                                {
                                    let l10 = *base.add(0).cast::<*mut u8>();
                                    let l11 = *base.add(4).cast::<usize>();
                                    _rt::cabi_dealloc(l10, l11, 1);
                                    let l12 = *base.add(8).cast::<*mut u8>();
                                    let l13 = *base.add(12).cast::<usize>();
                                    _rt::cabi_dealloc(l12, l13, 1);
                                }
                            }
                            _rt::cabi_dealloc(base14, len14 * 16, 4);
                            let l15 = *base.add(32).cast::<*mut u8>();
                            let l16 = *base.add(36).cast::<usize>();
                            _rt::cabi_dealloc(l15, l16, 1);
                        }
                    }
                    _rt::cabi_dealloc(base17, len17 * 40, 4);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_call_tool_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: *mut u8,
                    arg3: usize,
                    arg4: *mut u8,
                    arg5: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
                    let len1 = arg3;
                    let bytes1 = _rt::Vec::from_raw_parts(arg2.cast(), len1, len1);
                    let len2 = arg5;
                    let bytes2 = _rt::Vec::from_raw_parts(arg4.cast(), len2, len2);
                    let result3 = T::call_tool(
                        _rt::string_lift(bytes0),
                        _rt::string_lift(bytes1),
                        _rt::string_lift(bytes2),
                    );
                    let ptr4 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
                    let vec5 = (result3.into_bytes()).into_boxed_slice();
                    let ptr5 = vec5.as_ptr().cast::<u8>();
                    let len5 = vec5.len();
                    ::core::mem::forget(vec5);
                    *ptr4.add(4).cast::<usize>() = len5;
                    *ptr4.add(0).cast::<*mut u8>() = ptr5.cast_mut();
                    ptr4
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_call_tool<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0.add(4).cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_format_tools_for_prompt_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::format_tools_for_prompt();
                    let ptr1 = _RET_AREA.0.as_mut_ptr().cast::<u8>();
                    let vec2 = (result0.into_bytes()).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(4).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_format_tools_for_prompt<T: Guest>(
                    arg0: *mut u8,
                ) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0.add(4).cast::<usize>();
                    _rt::cabi_dealloc(l0, l1, 1);
                }
                pub trait Guest {
                    fn list_tools() -> _rt::Vec<ToolInfo>;
                    fn call_tool(
                        component_name: _rt::String,
                        function_name: _rt::String,
                        args_json: _rt::String,
                    ) -> _rt::String;
                    fn format_tools_for_prompt() -> _rt::String;
                }
                #[doc(hidden)]
                macro_rules! __export_asterbot_types_toolkit_1_0_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[export_name =
                        "asterbot:types/toolkit@1.0.0#list-tools"] unsafe extern "C" fn
                        export_list_tools() -> * mut u8 { $($path_to_types)*::
                        _export_list_tools_cabi::<$ty > () } #[export_name =
                        "cabi_post_asterbot:types/toolkit@1.0.0#list-tools"] unsafe
                        extern "C" fn _post_return_list_tools(arg0 : * mut u8,) {
                        $($path_to_types)*:: __post_return_list_tools::<$ty > (arg0) }
                        #[export_name = "asterbot:types/toolkit@1.0.0#call-tool"] unsafe
                        extern "C" fn export_call_tool(arg0 : * mut u8, arg1 : usize,
                        arg2 : * mut u8, arg3 : usize, arg4 : * mut u8, arg5 : usize,) ->
                        * mut u8 { $($path_to_types)*:: _export_call_tool_cabi::<$ty >
                        (arg0, arg1, arg2, arg3, arg4, arg5) } #[export_name =
                        "cabi_post_asterbot:types/toolkit@1.0.0#call-tool"] unsafe extern
                        "C" fn _post_return_call_tool(arg0 : * mut u8,) {
                        $($path_to_types)*:: __post_return_call_tool::<$ty > (arg0) }
                        #[export_name =
                        "asterbot:types/toolkit@1.0.0#format-tools-for-prompt"] unsafe
                        extern "C" fn export_format_tools_for_prompt() -> * mut u8 {
                        $($path_to_types)*:: _export_format_tools_for_prompt_cabi::<$ty >
                        () } #[export_name =
                        "cabi_post_asterbot:types/toolkit@1.0.0#format-tools-for-prompt"]
                        unsafe extern "C" fn _post_return_format_tools_for_prompt(arg0 :
                        * mut u8,) { $($path_to_types)*::
                        __post_return_format_tools_for_prompt::<$ty > (arg0) } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_asterbot_types_toolkit_1_0_0_cabi;
                #[repr(align(4))]
                struct _RetArea([::core::mem::MaybeUninit<u8>; 8]);
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            core::hint::unreachable_unchecked()
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_component_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::asterbot::types::toolkit::__export_asterbot_types_toolkit_1_0_0_cabi!($ty
        with_types_in $($path_to_types_root)*:: exports::asterbot::types::toolkit);
    };
}
#[doc(inline)]
pub(crate) use __export_component_impl as export;
#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:asterbot:toolkit@1.0.0:component:encoded world"]
#[doc(hidden)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1231] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xcf\x08\x01A\x02\x01\
A\x07\x01B!\x01r\x01\x07versions\x04\0\x0cruntime-info\x03\0\0\x01r\x03\x04names\
\x09type-names\x0btype-schemas\x04\0\x0aparam-info\x03\0\x02\x01r\x02\x09type-na\
mes\x0btype-schemas\x04\0\x09type-info\x03\0\x04\x01ks\x01p\x03\x01k\x05\x01r\x05\
\x04names\x0einterface-name\x06\x0bdescription\x06\x06inputs\x07\x06output\x08\x04\
\0\x0dfunction-info\x03\0\x09\x01ps\x01p\x0a\x01r\x05\x04names\x07versions\x0ain\
terfaces\x0b\x0bdescription\x06\x09functions\x0c\x04\0\x0ecomponent-info\x03\0\x0d\
\x01m\x05\x13component-not-found\x12function-not-found\x0cinvalid-args\x11invoca\
tion-failed\x14serialization-failed\x04\0\x0fcall-error-kind\x03\0\x0f\x01r\x02\x04\
kind\x10\x07messages\x04\0\x0acall-error\x03\0\x11\x01@\0\0\x01\x04\0\x10get-run\
time-info\x01\x13\x01p\x0e\x01@\0\0\x14\x04\0\x0flist-components\x01\x15\x04\0\x15\
list-other-components\x01\x15\x01k\x0e\x01@\x01\x04names\0\x16\x04\0\x0dget-comp\
onent\x01\x17\x01@\x02\x0ecomponent-names\x0einterface-names\0\x7f\x04\0\x14comp\
onent-implements\x01\x18\x01j\x01s\x01\x12\x01@\x03\x0ecomponent-names\x0dfuncti\
on-names\x09args-jsons\0\x19\x04\0\x17call-component-function\x01\x1a\x03\0\x16a\
sterai:host/api@1.0.0\x05\0\x01B\x05\x01r\x02\x04names\x09type-names\x04\0\x0ato\
ol-param\x03\0\0\x01p\x01\x01r\x05\x0ecomponent-names\x0dfunction-names\x0bdescr\
iptions\x06params\x02\x0breturn-types\x04\0\x09tool-info\x03\0\x03\x03\0\x1aaste\
rbot:types/types@1.0.0\x05\x01\x02\x03\0\x01\x09tool-info\x01B\x09\x02\x03\x02\x01\
\x02\x04\0\x09tool-info\x03\0\0\x01p\x01\x01@\0\0\x02\x04\0\x0alist-tools\x01\x03\
\x01@\x03\x0ecomponent-names\x0dfunction-names\x09args-jsons\0s\x04\0\x09call-to\
ol\x01\x04\x01@\0\0s\x04\0\x17format-tools-for-prompt\x01\x05\x04\0\x1casterbot:\
types/toolkit@1.0.0\x05\x03\x04\0\x20asterbot:toolkit/component@1.0.0\x04\0\x0b\x0f\
\x01\0\x09component\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compo\
nent\x070.220.0\x10wit-bindgen-rust\x060.36.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
