package asterbot:discord-gateway@0.1.0;

world component {
  import asterbot:types/agent@1.0.0;
  import asterai:discord/discord@0.1.0;
  export asterai:discord-message-listener/incoming-handler@0.1.0;
}
